### ISSUE TITLE
"Review Application", with invalid url/hash, could have better error handling

### ISSUE THREAD

**Issue by kaladay** [TexasDigitalLibrary/Vireo#1364]
The findone endpoint when finding by hash does not perform a NULL check.
This results in the error: `TypeError: model is null`.
It would be better to more gracefully handle the case where the review hash is not found and either return 404 or provide a cleaner way of presenting the error than simply showing `ERROR: (500) ` and showing a misleading `Loading Submission ...`.

**Comment by jameswsullivan** [comment]
I had an "Advisor Review URL" related problem recently and this seems to be the GitHub issue that's closely related for dropping the comments and context. In short, yes

1. the `getOne` and the `findOneByAdvisorAccessHash` stuff in [SubmissionController.java](https://github.com/TexasDigitalLibrary/Vireo/blob/9fe87304ad1628345cd6cf24c0dc497167c218ec/src/main/java/org/tdl/vireo/controller/SubmissionController.java#L234) should do null checks;
2. advisor review URL related stuff should display some meaningful message/error in the UI, rather than a generic 500 ribbon with a "Loading Submission ..." wording on the page. Also when email templates ([TemplateUtility.java](https://github.com/TexasDigitalLibrary/Vireo/blob/9fe87304ad1628345cd6cf24c0dc497167c218ec/src/main/java/org/tdl/vireo/utility/TemplateUtility.java#L74)) cannot fetch the advisor URL, it also just shows a 500 error in the UI and with a stack trace in the logs.

#### Context:

After V3 -> V4 migration, some advisor review URLs are gone, so when reviewers send email using templates that contain `{ADVISOR_URL}`, email sending would fail with the following stack trace:

```
ERROR 1 --- [nio-9000-exec-4] c.a.CustomResponseEntityExceptionHandler : null
DEBUG 1 --- [nio-9000-exec-4] c.a.CustomResponseEntityExceptionHandler : null
java.lang.NullPointerException: null
	at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1015) ~[na:na]
	at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:998) ~[na:na]
	at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1182) ~[na:na]
	at java.base/java.lang.String.replaceAll(String.java:2126) ~[na:na]
	at org.tdl.vireo.utility.TemplateUtility.compileString(TemplateUtility.java:74) ~[classes!/:na]
```

Then when I tried to see how to retrieve/regenerate that review URL, I saw that it's [just a random UUID with dashes removed](https://github.com/TexasDigitalLibrary/Vireo/blob/9fe87304ad1628345cd6cf24c0dc497167c218ec/src/main/java/org/tdl/vireo/model/Submission.java#L583) and then placed in the database, so I generated one. But at first I only put the URL in the `advisor_reviewurl` column in the `submission` table and didn't see the `advisor_access_hash` column, that was where I got the "Loading Submission ..." page when accessing that new review URL:

```
SELECT id,advisor_access_hash,advisor_reviewurl FROM submission WHERE id = 12345;
```

<img width="600" alt="Image" src="https://github.com/user-attachments/assets/b32a8df5-a6af-41b7-9fed-3a3943c21b7d" />

This also happens when a submission is "In Progress" and the UUID and URL don't exist yet.

Recreating the URL is fairly easy, postgres can do it directly via:

```
WITH new_hash AS (
    SELECT replace(gen_random_uuid()::text, '-', '') AS hash
)
UPDATE submission
SET advisor_access_hash = new_hash.hash, advisor_reviewurl = 'https://myvireo.com/review/' || new_hash.hash
FROM new_hash
WHERE id = 12345;
```
